### PR TITLE
Fix Compiler Warnings

### LINKED ISSUE #448: Compile warnings when building source code
The gcc compiler produces several compiler warnings when building the source code:

```
src/access-broker.c:592:12: warning: Dereference of null pointer (loaded from variable 'count')
    *count = capability_data.data.handles.count;
     ~~~~~ ^
1 warning generated.

  CC       test/test_resource_manager_unit-resource-manager_unit.o
test/resource-manager_unit.c:382:17: warning: Function call argument is an uninitialized value
        entry = handle_map_entry_new (phandles [i], vhandles [i]);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.

  CC       test/test_tss2_tcti_tabrmd_unit-tss2-tcti-tabrmd_unit.o
test/tss2-tcti-tabrmd_unit.c:453:9: warning: Potential leak of memory pointed to by 'data'
        perror ("calloc");
        ^~~~~~
test/tss2-tcti-tabrmd_unit.c:604:5: warning: Access to field 'state' results in a dereference of a null pointer (loaded from field 'context')
    assert_int_equal (TSS2_TCTI_TABRMD_STATE (data->context),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test/tss2-tcti-tabrmd_unit.c:783:5: warning: Access to field 'state' results in a dereference of a null pointer (loaded from field 'context')
    assert_int_equal (TSS2_TCTI_TABRMD_STATE (data->context),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test/tss2-tcti-tabrmd_unit.c:824:5: warning: Access to field 'state' results in a dereference of a null pointer (loaded from field 'context')
    assert_int_equal (TSS2_TCTI_TABRMD_STATE (data->context),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test/tss2-tcti-tabrmd_unit.c:835:13: warning: Value stored to 'command_in' during its initialization is never read
    uint8_t command_in [] = { 0x80, 0x02,
            ^~~~~~~~~~      ~~~~~~~~~~~~~
test/tss2-tcti-tabrmd_unit.c:859:13: warning: Value stored to 'command_in' during its initialization is never read
    uint8_t command_in [] = { 0x80, 0x02,
            ^~~~~~~~~~      ~~~~~~~~~~~~~
test/tss2-tcti-tabrmd_unit.c:960:13: warning: Value stored to 'command_in' during its initialization is never read
    uint8_t command_in [] = { 0x80, 0x02,
            ^~~~~~~~~~      ~~~~~~~~~~~~~
test/tss2-tcti-tabrmd_unit.c:1023:5: warning: Access to field 'state' results in a dereference of a null pointer (loaded from field 'context')
    assert_int_equal (TSS2_TCTI_TABRMD_STATE (data->context),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test/tss2-tcti-tabrmd_unit.c:1055:5: warning: Access to field 'state' results in a dereference of a null pointer (loaded from field 'context')
    assert_int_equal (TSS2_TCTI_TABRMD_STATE (data->context),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test/tss2-tcti-tabrmd_unit.c:1088:5: warning: Access to field 'state' results in a dereference of a null pointer (loaded from field 'context')
    assert_int_equal (TSS2_TCTI_TABRMD_STATE (data->context),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test/tss2-tcti-tabrmd_unit.c:1120:5: warning: Access to field 'state' results in a dereference of a null pointer (loaded from field 'context')
    assert_int_equal (TSS2_TCTI_TABRMD_STATE (data->context),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test/tss2-tcti-tabrmd_unit.c:1207:5: warning: Access to field 'state' results in a dereference of a null pointer (loaded from field 'context')
    assert_int_equal (TSS2_TCTI_TABRMD_STATE (data->context),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test/tss2-tcti-tabrmd_unit.c:1241:5: warning: Access to field 'state' results in a dereference of a null pointer (loaded from field 'context')
    assert_int_equal (TSS2_TCTI_TABRMD_STATE (data->context),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test/tss2-tcti-tabrmd_unit.c:1278:5: warning: Access to field 'state' results in a dereference of a null pointer (loaded from field 'context')
    assert_int_equal (TSS2_TCTI_TABRMD_STATE (data->context),
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
test/tss2-tcti-tabrmd_unit.c:1368:10: warning: Access to field 'sock_connect' results in a dereference of a null pointer (loaded from field 'context')
    fd = TSS2_TCTI_TABRMD_FD (data->context);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./src/tcti-tabrmd-priv.h:64:22: note: expanded from macro 'TSS2_TCTI_TABRMD_FD'
    g_socket_get_fd (TSS2_TCTI_TABRMD_SOCKET (context))
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./src/tcti-tabrmd-priv.h:62:37: note: expanded from macro 'TSS2_TCTI_TABRMD_SOCKET'
    g_socket_connection_get_socket (TSS2_TCTI_TABRMD_SOCK_CONNECT (context))
                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./src/tcti-tabrmd-priv.h:60:5: note: expanded from macro 'TSS2_TCTI_TABRMD_SOCK_CONNECT'
    ((TSS2_TCTI_TABRMD_CONTEXT*)context)->sock_connect
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
15 warnings generated.

  CC       test/test_tss2_tcti_echo_unit-tss2-tcti-echo_unit.o
test/tss2-tcti-echo_unit.c:343:53: warning: Access to field 'buf_size' results in a dereference of a null pointer (loaded from variable 'echo_context')
    assert_memory_equal (buffer, echo_context->buf, echo_context->buf_size);
                                                    ^~~~~~~~~~~~~~~~~~~~~~
```

### PR DESCRIPTION
**Pull request by danintel**
Fix compiler warnings about possible NULL pointer dereferences,
memory leaks, and unused variables.

Fixes #448.

Signed-off-by: Dan Anderson <daniel.anderson@intel.com>

### CODE REVIEW

File: src/access-broker.c [hunk 1]
```diff
@@ -589,7 +589,8 @@ access_broker_get_trans_object_count (AccessBroker *broker,
                                  NULL);
     if (rc != TSS2_RC_SUCCESS)
         goto out;
-    *count = capability_data.data.handles.count;
+    if (count != NULL)
```
Comment (tstruk) [inline src/access-broker.c]: There is a check for it above in line 575 g_assert_nonnull (count);

File: test/integration/get-capability-handles-transient.int.c [hunk 2]
```diff
@@ -189,9 +189,10 @@ test_invoke (TSS2_SYS_CONTEXT *sapi_context)
     TPM2_HANDLE          *handles_load;
     TPM2_HANDLE          *handles_query;
     size_t               handles_count;
-    char                *env_str         = NULL, *end_ptr = NULL;
+    char                 *env_str        = NULL, *end_ptr = NULL;
```
Comment (flihp) [inline test/integration/get-capability-handles-transient.int.c]: Doesn't look like any functional change on this line. Just whitespace noise?

File: test/tss2-tcti-tabrmd_unit.c [hunk 3]
```diff
@@ -839,6 +847,8 @@ tcti_tabrmd_receive_poll_fail_test (void **state)
     uint8_t command_out [sizeof (command_in)] = { 0 };
     TSS2_RC rc;
 
+    (void)command_in;
```
Comment (flihp) [inline test/tss2-tcti-tabrmd_unit.c]: Assuming this is to cope with an unused parameter. Any reason you didn't use the `UNUSED_PARAM` macro from `src/util.h`?

File: test/tss2-tcti-tabrmd_unit.c [hunk 4]
```diff
@@ -965,6 +975,8 @@ tcti_tabrmd_receive_bad_timeout_test (void **state)
...
```
Comment (flihp) [inline test/tss2-tcti-tabrmd_unit.c]: same as above

File: src/access-broker.c (hunk 1 above)
Comment (danintel) [reply src/access-broker.c]: Yes.  The compiler doesn't seem to know that it checks for NULL and (I suppose?) stops execution or something.

File: test/integration/get-capability-handles-transient.int.c (hunk 2 above)
Comment (danintel) [reply test/integration/get-capability-handles-transient.int.c]: The column is not aligned with any of the other lines.  I will restore the error.

File: test/tss2-tcti-tabrmd_unit.c (hunk 3 above)
Comment (danintel) [reply test/tss2-tcti-tabrmd_unit.c]: It's not a parameter.  But I will use it.

File: test/tss2-tcti-tabrmd_unit.c (hunk 4 above)
Comment (danintel) [reply test/tss2-tcti-tabrmd_unit.c]: Same as above for me too.

File: src/access-broker.c (hunk 1 above)
Comment (flihp) [reply src/access-broker.c]: Any chance we can use something like the coverity model files for this? I had to create a simple model file to teach coverity how g_error works here: https://github.com/tpm2-software/tpm2-abrmd/blob/master/coverity/coverity-model.c

File: test/integration/get-capability-handles-transient.int.c (hunk 2 above)
Comment (flihp) [reply test/integration/get-capability-handles-transient.int.c]: I've learned the hard way that spacing things like this is a terrible idea (but "it seemed like a good idea at the time"). Well-intentioned folks like yourself try to align things or clean up alignment that got out of wack and just end up creating messy patches. If you want to clean this stuff up then just remove it and please do so in a patch dedicated to the cleanup.

File: test/tss2-tcti-tabrmd_unit.c (hunk 3 above)
Comment (flihp) [reply test/tss2-tcti-tabrmd_unit.c]: Sounds like the macro is misnamed then: should just be `UNUSED`.

File: src/access-broker.c (hunk 1 above)
Comment (danintel) [reply src/access-broker.c]: That would be nice. I seen it in other static analysis software, but not in scan-build.

File: test/integration/get-capability-handles-transient.int.c (hunk 2 above)
Comment (danintel) [reply test/integration/get-capability-handles-transient.int.c]: I think it's silly to leave formatting problems unfixed. It makes the code harder to read.
Some code is indented 4 spaces, some 2, or 3.  Some functions have a mixture of indentation.
I see other pull requests here by everyone else that fix formatting.

But I restored it to the way it originally was--so the issue is mute.

File: test/tss2-tcti-tabrmd_unit.c (hunk 3 above)
Comment (danintel) [reply test/tss2-tcti-tabrmd_unit.c]: I added a UNUSED_VAR macro.

File: src/access-broker.c (hunk 1 above)
Comment (danintel) [reply src/access-broker.c]: I thought about this some more and I think I can kludge in a coverity-like model using #define for scan-build.

Comment (flihp) [reply src/access-broker.c]: I just punched 'scan-build glib' into the googles and this was the first hit: https://www.freedesktop.org/software/tartan/ ... might be useful.

Comment (flihp) [reply src/access-broker.c]: whoops, this isn't the scan-build thread. My mistake. So this is a newer version of GCC presumably with some static analysis stuff built in.

**Comment by danintel** [comment]
Separated out memory leaks and uninitialized variables to separate issue #465, pull request #466.

**Comment by danintel** [comment]
I will look at this and determine if the compiler warnings come from clang 3.8, clang 5.0, scan-build 3.8, or scan-build 5.0

**Comment by danintel** [comment]
@flihp, to answer your offline question:
The warnings above come from scan-build  (both 3.8 and 5.0).
Running gcc or clang (3.8 or 5.0) alone do not produce these warnings.

These changes are mainly to remove all warnings from the build so new warnings will be more visible.

This code is ready to integrate.

**Comment by danintel** [comment]
Rebased branch.  Still waiting for approval or feedback.
